### ISSUE TITLE
feature: asdon tab category to fuel asdon martin

### ISSUE THREAD

**Issue by Malibu-Stacey** [pstalcup/keeping-tabs#3]
Some stuff is better off used as asdon martin fuel than autoselling or trying to sell at mall min.
CLI command for fueling asdon martin is `asdonmartin fuel [amount] item name`

**Comment by pstalcup** [comment]
For this tab - do you just want to always convert items in that tab to fuel? Would you only want to convert them if you are below a specific fuel level?

**Comment by Malibu-Stacey** [comment]
I would make it easy & just always convert. If you want to be fancy maybe use a property to check if fuel is currently below it & then only fuel until it hits that.

**Comment by pstalcup** [comment]
Added in the newest build
